import { assetPath } from "../utils/assetPath";

export const animations = [
  {
    id: "animation-001",
    title: "",
    video: assetPath("assets/animation/pour-cassie.mp4"),
    poster: assetPath("assets/animation/miniature/cassie.jpg"),
    category: "court-métrage",
    duration: null,
    date: "2022-12-12",
    year: 2022,
    alt: "court-métrage 01",
    featured: false,
    type: "video",
  },
  {
    id: "animation-002",
    title: "",
    video: assetPath("assets/animation/anime-transformation-v2.gif"),
    poster: "",
    category: "animation 2d",
    duration: null,
    date: "2025-02-01",
    year: 2025,
    alt: "animation 2d 01",
    featured: false,
    type: "image",
  },
  {
    id: "animation-003",
    title: "",
    video: assetPath("assets/animation/disparition.mp4"),
    poster: assetPath("assets/animation/miniature/disparition.jpg"),
    category: "animation 2d",
    duration: null,
    date: "2023-07-15",
    year: 2023,
    alt: "animation 2d 02",
    featured: false,
    type: "video",
  },
  {
    id: "animation-004",
    title: "",
    video: assetPath("assets/animation/petite-fille.mp4"),
    poster: assetPath("assets/animation/miniature/petite-fille.jpg"),
    category: "animation 2d",
    duration: null,
    date: "2022-08-30",
    year: 2022,
    alt: "animation 2d 03",
    featured: false,
    type: "video",
  },
  {
    id: "animation-005",
    title: "",
    video: assetPath("assets/animation/chanteuse.mp4"),
    poster: assetPath("assets/animation/miniature/chanteuse.jpg"),
    category: "animation 2d",
    duration: null,
    date: "2022-08-30",
    year: 2022,
    alt: "animation 2d 03",
    featured: false,
    type: "video",
  },
  {
    id: "animation-006",
    title: "",
    video: assetPath("assets/animation/turn-arround.mp4"),
    poster: assetPath("assets/animation/miniature/turn-arround.jpg"),
    category: "animation 2d",
    duration: null,
    date: "2022-08-30",
    year: 2022,
    alt: "animation 2d 03",
    featured: false,
    type: "video",
  },
];
