import { assetPath } from "../utils/assetPath";

export const animations = [
  {
    "id": "animation-001",
    "title": "Short film (Rough)",
    "video": assetPath("assets/animation/pour-cassie.mp4"),
    "poster": assetPath("assets/animation/miniature/cassie.jpg"),
    "category": "court-métrage",
    "duration": null,
    "date": "2020-06-03",
    "year": 2020,
    "alt": "Short film",
    "featured": false,
    "type": "video"
  },
  {
    "id": "animation-002",
    "title": "Move",
    "video": assetPath("assets/animation/anime-transformation-v2.gif"),
    "poster": "",
    "category": "animation 2d",
    "duration": null,
    "date": "2016-02-01",
    "year": 2016,
    "alt": "Move 2d",
    "featured": false,
    "type": "image"
  },
  {
    "id": "animation-003",
    "title": "Effect teleport",
    "video": assetPath("assets/animation/disparition.mp4"),
    "poster": assetPath("assets/animation/miniature/disparition.jpg"),
    "category": "animation 2d",
    "duration": null,
    "date": "2019-08-01",
    "year": 2019,
    "alt": "Effect teleport",
    "featured": false,
    "type": "video"
  },
  {
    "id": "animation-004",
    "title": "Little girl",
    "video": assetPath("assets/animation/petite-fille.mp4"),
    "poster": assetPath("assets/animation/miniature/petite-fille.jpg"),
    "category": "animation 2d",
    "duration": null,
    "date": "2019-04-30",
    "year": 2019,
    "alt": "Little girl",
    "featured": false,
    "type": "video"
  },
  {
    "id": "animation-005",
    "title": "Sing",
    "video": assetPath("assets/animation/chanteuse.mp4"),
    "poster": assetPath("assets/animation/miniature/chanteuse.jpg"),
    "category": "animation 2d",
    "duration": null,
    "date": "2019-07-30",
    "year": 2019,
    "alt": "Sing",
    "featured": false,
    "type": "video"
  },
  {
    "id": "animation-006",
    "title": "Turn arround (Mecha)",
    "video": assetPath("assets/animation/turn-arround.mp4"),
    "poster": assetPath("assets/animation/miniature/turn-arround.jpg"),
    "category": "animation 2d",
    "duration": null,
    "date": "2019-02-15",
    "year": 2019,
    "alt": "turn arround",
    "featured": false,
    "type": "video"
  },
  {
    "id": "pose-fight",
    "title": "Pose fight",
    "video": assetPath("assets/animation/2026-07-23-02-12-04.mp4"),
    "poster": assetPath("assets/animation/miniature/2026-07-23-02-12-04-miniature.png"),
    "category": "animation 2d",
    "duration": null,
    "date": "2020-01-29",
    "year": 2020,
    "alt": "Pose fight",
    "featured": false,
    "type": "video"
  },
  {
    "id": "sketch-animation",
    "title": "Sketch animation",
    "video": assetPath("assets/animation/2026-07-23-02-13-54.mp4"),
    "poster": assetPath("assets/animation/miniature/2026-07-23-02-13-54-m.png"),
    "category": "animation 2d",
    "duration": null,
    "date": "2019-03-03",
    "year": 2019,
    "alt": "Sketch animation",
    "featured": false,
    "type": "video"
  },
  {
    "id": "scene",
    "title": "Scene",
    "video": assetPath("assets/animation/scene-1.mp4"),
    "poster": assetPath("assets/animation/miniature/scene-1-m.png"),
    "category": "animation 2d",
    "duration": null,
    "date": "2016-08-25",
    "year": 2016,
    "alt": "Scene",
    "featured": false,
    "type": "video"
  },
  {
    "id": "short-animation",
    "title": "Sketch animation",
    "video": assetPath("assets/animation/02.mp4"),
    "poster": assetPath("assets/animation/miniature/02-m.png"),
    "category": "animation 2d",
    "duration": null,
    "date": "2019-03-05",
    "year": 2019,
    "alt": "Sketch animation",
    "featured": false,
    "type": "video"
  },
  {
    "id": "short-animation-2",
    "title": "Short animation",
    "video": assetPath("assets/animation/short-animation.mp4"),
    "poster": assetPath("assets/animation/miniature/short-animation-miniature.png"),
    "category": "animation 2d",
    "duration": null,
    "date": "2020-04-21",
    "year": 2020,
    "alt": "Short animation",
    "featured": false,
    "type": "video"
  },
  {
    "id": "intro-after-effect",
    "title": "Intro after effect",
    "video": assetPath("assets/animation/index-v1-a1-720p-aac-4.mp4"),
    "poster": assetPath("assets/animation/miniature/index-v1-a1-720p-aac-3-miniature.png"),
    "category": "animation 3d",
    "duration": null,
    "date": "2018-07-01",
    "year": 2018,
    "alt": "Intro after effect",
    "featured": false,
    "type": "video"
  }
];
