import { assetPath } from "../utils/assetPath";

const mangaDefinitions = [
  {
    "id": "legend-of-animiste",
    "slug": "legend-of-animiste",
    "route": "/mangas/legend-of-animiste",
    "title": "Legend of Animiste",
    "edition": "",
    "cover": assetPath("assets/mangaka/completed-manga/legend-of-animiste/300x300-v2.jpg"),
    "banner": assetPath("assets/mangaka/completed-manga/legend-of-animiste/447x200.jpg"),
    "summary": "Legend of Animiste follows a young fighter drawn into a world shaped by spirits, ancient powers, and dangerous conflicts.\n\nDiscover the story of Legend of Animiste.",
    "genre": "",
    "role": "",
    "year": "",
    "readingDirection": "rtl",
    "defaultLanguage": "en",
    "languages": {
      "en": {
        "label": "English",
        "shortLabel": "ENG",
        "pages": [
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/english/Legend of animiste_Kevgenga_Page_01_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/english/Legend of animiste_Kevgenga_Page_02_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/english/Legend of animiste_Kevgenga_Page_03_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/english/Legend of animiste_Kevgenga_Page_04_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/english/Legend of animiste_Kevgenga_Page_05_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/english/Legend of animiste_Kevgenga_Page_06_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/english/Legend of animiste_Kevgenga_Page_07_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/english/Legend of animiste_Kevgenga_Page_08_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/english/Legend of animiste_Kevgenga_Page_09_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/english/Legend of animiste_Kevgenga_Page_10_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/english/Legend of animiste_Kevgenga_Page_11_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/english/Legend of animiste_Kevgenga_Page_12_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/english/Legend of animiste_Kevgenga_Page_13_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/english/Legend of animiste_Kevgenga_Page_14_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/english/Legend of animiste_Kevgenga_Page_15_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/english/Legend of animiste_Kevgenga_Page_16_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/english/Legend of animiste_Kevgenga_Page_17_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/english/Legend of animiste_Kevgenga_Page_18_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/english/Legend of animiste_Kevgenga_Page_19_Image_0001.jpg")
        ]
      },
      "fr": {
        "label": "French",
        "shortLabel": "FR",
        "pages": [
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/french/Legend of animiste_Kevgenga_Page_01_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/french/Legend of animiste_Kevgenga_Page_02_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/french/Legend of animiste_Kevgenga_Page_03_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/french/Legend of animiste_Kevgenga_Page_04_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/french/Legend of animiste_Kevgenga_Page_05_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/french/Legend of animiste_Kevgenga_Page_06_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/french/Legend of animiste_Kevgenga_Page_07_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/french/Legend of animiste_Kevgenga_Page_08_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/french/Legend of animiste_Kevgenga_Page_09_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/french/Legend of animiste_Kevgenga_Page_10_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/french/Legend of animiste_Kevgenga_Page_11_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/french/Legend of animiste_Kevgenga_Page_12_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/french/Legend of animiste_Kevgenga_Page_13_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/french/Legend of animiste_Kevgenga_Page_14_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/french/Legend of animiste_Kevgenga_Page_15_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/french/Legend of animiste_Kevgenga_Page_16_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/french/Legend of animiste_Kevgenga_Page_17_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/french/Legend of animiste_Kevgenga_Page_18_Image_0001.jpg"),
          assetPath("assets/mangaka/completed-manga/legend-of-animiste/french/Legend of animiste_Kevgenga_Page_19_Image_0001.jpg")
        ]
      }
    },
    "featured": false,
    "description": "",
    "author": "",
    "date": "",
    "status": "published",
    "visibility": "public",
    "defaultReadingMode": "",
    "tags": [],
    "order": 0,
    "presentationSection": "completed"
  },
  {
    "id": 2,
    "slug": "stubborn-love",
    "route": "/mangas/2",
    "title": "Stubborn love",
    "edition": "",
    "cover": assetPath("assets/mangaka/completed-manga/stubborn-love/300x300.jpg"),
    "banner": assetPath("assets/mangaka/completed-manga/stubborn-love/bandeau.jpg"),
    "summary": "Two childhood friends, Stubborn and Love, are brought to death's door after a fatal accident. Will they survive? The truth about their feelings reaches its climax. Discover the story of Stubborn Love.",
    "genre": "",
    "role": "",
    "year": "",
    "readingDirection": "rtl",
    "defaultLanguage": "en",
    "languages": {
      "en": {
        "label": "English",
        "shortLabel": "ENG",
        "pages": [
          assetPath("assets/mangaka/completed-manga/stubborn-love/english/01.jpg"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/english/02.jpg"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/english/03.jpg"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/english/04.jpg"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/english/05.jpg"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/english/06.jpg"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/english/07.jpg"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/english/08.jpg"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/english/09.jpg"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/english/10.jpg"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/english/11.jpg"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/english/12.jpg"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/english/13.jpg")
        ]
      },
      "fr": {
        "label": "French",
        "shortLabel": "FR",
        "pages": [
          assetPath("assets/mangaka/completed-manga/stubborn-love/french/01.webp"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/french/02.webp"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/french/03.webp"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/french/04.webp"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/french/05.webp"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/french/06.webp"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/french/07.webp"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/french/08.webp"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/french/09.webp"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/french/10.webp"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/french/11.webp"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/french/12.webp"),
          assetPath("assets/mangaka/completed-manga/stubborn-love/french/13.webp")
        ]
      }
    },
    "featured": false,
    "presentationSection": "completed"
  },
  {
    "id": 3,
    "slug": "ahes",
    "route": "/mangas/3",
    "title": "Ahès",
    "edition": "",
    "cover": assetPath("assets/mangaka/completed-manga/ahes/page_001.jpg"),
    "banner": "",
    "summary": "Locked away in her castle for centuries, Princess Ahès finally escapes to discover the outside world that had been forbidden to her. Faced with the destruction of her kingdom, she will have to fight against her destiny. Discover the story of Ahès.",
    "genre": "",
    "role": "",
    "year": "",
    "readingDirection": "rtl",
    "defaultLanguage": "original",
    "languages": {
      "original": {
        "label": "Original",
        "shortLabel": "ORIG",
        "pages": [
          assetPath("assets/mangaka/completed-manga/ahes/page_001.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_002.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_003.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_004.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_005.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_006.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_007.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_008.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_009.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_010.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_011.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_012.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_013.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_014.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_015.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_016.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_017.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_018.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_019.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_020.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_021.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_022.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_023.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_024.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_025.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_026.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_027.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_028.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_029.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_030.jpg"),
          assetPath("assets/mangaka/completed-manga/ahes/page_031.jpg")
        ]
      }
    },
    "featured": false,
    "presentationSection": "completed"
  },
  {
    "id": "ancient-animiste-god",
    "slug": "ancient-animiste-god",
    "route": "/mangas/ancient-animiste-god",
    "title": "Ancient God",
    "edition": "",
    "banner": assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/banner.jpg"),
    "presentationSection": "storyboard",
    "summary": "Sketch Storyboard",
    "genre": "",
    "role": "",
    "year": "",
    "readingDirection": "rtl",
    "defaultLanguage": "english",
    "languages": {
      "english": {
        "label": "ENGLISH",
        "shortLabel": "ENGLISH",
        "pages": [
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/00.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/01.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/2.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/cd01-01-01.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/cd01-02.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/cd01-2.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/cd01-04.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/cd01.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251201-021621.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251206-090553.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251206-122819.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251206-123011.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251206-124541.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251206-132057.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251206-132108.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251206-132118.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251206-132127.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251206-132138.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251206-132150.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251206-133726.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251206-133922.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251206-135459-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251206-135459.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251207-091429.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251207-092215.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251207-092323.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251207-093146.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251207-093238.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251207-093708.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251207-094043.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251207-094335.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251207-095009.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251207-095536.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251207-100117.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251207-100521.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251207-100552.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251207-100833.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251207-102430-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251207-102430.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251207-102447.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251207-103531.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251207-104026.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251212-112514.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251212-112816.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251212-113201.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251212-113304.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251212-121750.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251212-122426.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/english/penup-20251226-090722.jpg")
        ]
      },
      "french": {
        "label": "FRENCH",
        "shortLabel": "FRENCH",
        "pages": [
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/00.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/01.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/2.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/cd01-01-01.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/cd01-02.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/cd01-2.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/cd01-04.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/cd01.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251201-021621.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251206-090553.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251206-122819.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251206-123011.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251206-124541.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251206-132057.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251206-132108.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251206-132118.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251206-132127.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251206-132138.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251206-132150.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251206-133726.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251206-133922.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251206-135459-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251206-135459.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251207-091429.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251207-092215.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251207-092323.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251207-093146.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251207-093238.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251207-093708.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251207-094043.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251207-094335.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251207-095009.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251207-095536.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251207-100117.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251207-100521.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251207-100552.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251207-100833.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251207-102430-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251207-102430.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251207-102447.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251207-103531.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251207-104026.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251212-112514.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251212-112816.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251212-113201.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251212-113304.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251212-121750.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251212-122426.jpg"),
          assetPath("assets/mangaka/complete-storyboards/ancient-animiste-god/french/penup-20251226-090722.jpg")
        ]
      }
    },
    "featured": false,
    "status": "draft",
    "visibility": "public",
    "description": "",
    "author": "",
    "date": "",
    "defaultReadingMode": "",
    "tags": [],
    "order": 1
  },
  {
    "id": "blade-moine",
    "slug": "blade-moine",
    "route": "/mangas/blade-moine",
    "title": "Blade & Moine",
    "edition": "",
    "banner": assetPath("assets/mangaka/complete-storyboards/blade-moine/banner.jpg"),
    "presentationSection": "storyboard",
    "summary": "Sketch Storyboard",
    "genre": "",
    "role": "",
    "year": "",
    "readingDirection": "rtl",
    "defaultLanguage": "orig",
    "languages": {
      "orig": {
        "label": "Original",
        "shortLabel": "ORIG",
        "pages": [
          assetPath("assets/mangaka/complete-storyboards/blade-moine/orig/penup-20260128-084952.jpg"),
          assetPath("assets/mangaka/complete-storyboards/blade-moine/orig/penup-20260128-085503.jpg"),
          assetPath("assets/mangaka/complete-storyboards/blade-moine/orig/penup-20260128-090221.jpg"),
          assetPath("assets/mangaka/complete-storyboards/blade-moine/orig/penup-20260128-091207.jpg"),
          assetPath("assets/mangaka/complete-storyboards/blade-moine/orig/penup-20260128-094632-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/blade-moine/orig/penup-20260128-094632-2.jpg"),
          assetPath("assets/mangaka/complete-storyboards/blade-moine/orig/penup-20260128-094632-3.jpg"),
          assetPath("assets/mangaka/complete-storyboards/blade-moine/orig/penup-20260128-094632-4.jpg"),
          assetPath("assets/mangaka/complete-storyboards/blade-moine/orig/penup-20260128-094632-5.jpg"),
          assetPath("assets/mangaka/complete-storyboards/blade-moine/orig/penup-20260128-094632-6-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/blade-moine/orig/penup-20260128-094632-6.jpg"),
          assetPath("assets/mangaka/complete-storyboards/blade-moine/orig/penup-20260128-094632-9.jpg"),
          assetPath("assets/mangaka/complete-storyboards/blade-moine/orig/penup-20260128-094632-10.jpg"),
          assetPath("assets/mangaka/complete-storyboards/blade-moine/orig/penup-20260128-094632.jpg"),
          assetPath("assets/mangaka/complete-storyboards/blade-moine/orig/penup-20260128-101255-1-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/blade-moine/orig/penup-20260128-101255-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/blade-moine/orig/penup-20260128-101255-2-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/blade-moine/orig/penup-20260128-101255-2.jpg"),
          assetPath("assets/mangaka/complete-storyboards/blade-moine/orig/penup-20260128-101255.jpg"),
          assetPath("assets/mangaka/complete-storyboards/blade-moine/orig/penup-20260128-102323.jpg"),
          assetPath("assets/mangaka/complete-storyboards/blade-moine/orig/penup-20260128-103135.jpg"),
          assetPath("assets/mangaka/complete-storyboards/blade-moine/orig/penup-20260505-012034.jpg"),
          assetPath("assets/mangaka/complete-storyboards/blade-moine/orig/projet-20260129095243.jpg")
        ]
      }
    },
    "featured": false,
    "status": "draft",
    "visibility": "public",
    "description": "",
    "author": "",
    "date": "",
    "defaultReadingMode": "",
    "tags": [],
    "order": 0
  },
  {
    "id": "exorcist-vs-shaman",
    "slug": "exorcist-vs-shaman",
    "route": "/mangas/exorcist-vs-shaman",
    "title": "Exorcist vs. Shaman",
    "edition": "",
    "banner": assetPath("assets/mangaka/complete-storyboards/exorcist-vs-shaman/banner.jpg"),
    "presentationSection": "storyboard",
    "summary": "Sketch Storyboard",
    "genre": "",
    "role": "",
    "year": "",
    "readingDirection": "rtl",
    "defaultLanguage": "orig",
    "languages": {
      "orig": {
        "label": "Original",
        "shortLabel": "ORIG",
        "pages": [
          assetPath("assets/mangaka/complete-storyboards/exorcist-vs-shaman/orig/penup-20260506-014804.jpg"),
          assetPath("assets/mangaka/complete-storyboards/exorcist-vs-shaman/orig/penup-20260508-050719.jpg"),
          assetPath("assets/mangaka/complete-storyboards/exorcist-vs-shaman/orig/penup-20260508-052252.jpg"),
          assetPath("assets/mangaka/complete-storyboards/exorcist-vs-shaman/orig/penup-20260508-053610.jpg"),
          assetPath("assets/mangaka/complete-storyboards/exorcist-vs-shaman/orig/penup-20260508-054818.jpg"),
          assetPath("assets/mangaka/complete-storyboards/exorcist-vs-shaman/orig/penup-20260508-055925.jpg"),
          assetPath("assets/mangaka/complete-storyboards/exorcist-vs-shaman/orig/penup-20260508-060614.jpg")
        ]
      }
    },
    "featured": false,
    "status": "draft",
    "visibility": "public",
    "description": "",
    "author": "",
    "date": "",
    "defaultReadingMode": "",
    "tags": [],
    "order": 0
  },
  {
    "id": "good-travel-brother-sister-kyodai",
    "slug": "good-travel-brother-sister-kyodai",
    "route": "/mangas/good-travel-brother-sister-kyodai",
    "title": "Good Travel - Brother Sister (Kyôdaï)",
    "edition": "",
    "banner": assetPath("assets/mangaka/complete-storyboards/good-travel-brother-sister-kyodai/banner-2.jpg"),
    "presentationSection": "storyboard",
    "summary": "Sketch storyboard",
    "genre": "",
    "role": "",
    "year": "",
    "readingDirection": "rtl",
    "defaultLanguage": "orig",
    "languages": {
      "orig": {
        "label": "Original",
        "shortLabel": "ORIG",
        "pages": [
          assetPath("assets/mangaka/complete-storyboards/good-travel-brother-sister-kyodai/orig/penup-20251227-091557.jpg"),
          assetPath("assets/mangaka/complete-storyboards/good-travel-brother-sister-kyodai/orig/penup-20251227-092313.jpg"),
          assetPath("assets/mangaka/complete-storyboards/good-travel-brother-sister-kyodai/orig/penup-20251227-093741-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/good-travel-brother-sister-kyodai/orig/penup-20251227-093741.jpg"),
          assetPath("assets/mangaka/complete-storyboards/good-travel-brother-sister-kyodai/orig/penup-20251227-095729.jpg"),
          assetPath("assets/mangaka/complete-storyboards/good-travel-brother-sister-kyodai/orig/penup-20251227-095744.jpg"),
          assetPath("assets/mangaka/complete-storyboards/good-travel-brother-sister-kyodai/orig/penup-20251227-102307.jpg"),
          assetPath("assets/mangaka/complete-storyboards/good-travel-brother-sister-kyodai/orig/penup-20251227-102326-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/good-travel-brother-sister-kyodai/orig/penup-20251227-102326.jpg"),
          assetPath("assets/mangaka/complete-storyboards/good-travel-brother-sister-kyodai/orig/penup-20251228-123605.jpg"),
          assetPath("assets/mangaka/complete-storyboards/good-travel-brother-sister-kyodai/orig/penup-20251228-124416.jpg"),
          assetPath("assets/mangaka/complete-storyboards/good-travel-brother-sister-kyodai/orig/penup-20251228-124613.jpg"),
          assetPath("assets/mangaka/complete-storyboards/good-travel-brother-sister-kyodai/orig/penup-20251228-125451.jpg"),
          assetPath("assets/mangaka/complete-storyboards/good-travel-brother-sister-kyodai/orig/penup-20251228-130405-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/good-travel-brother-sister-kyodai/orig/penup-20251228-130405-2.jpg"),
          assetPath("assets/mangaka/complete-storyboards/good-travel-brother-sister-kyodai/orig/penup-20251228-130405.jpg")
        ]
      }
    },
    "featured": false,
    "status": "draft",
    "visibility": "public",
    "description": "",
    "author": "",
    "date": "",
    "defaultReadingMode": "",
    "tags": [],
    "order": 0
  },
  {
    "id": "gotenga-x-so",
    "slug": "gotenga-x-so",
    "route": "/mangas/gotenga-x-so",
    "title": "Gotenga X So",
    "edition": "",
    "banner": assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/banner.jpg"),
    "presentationSection": "storyboard",
    "summary": "Sketch Storyboard",
    "genre": "",
    "role": "",
    "year": "",
    "readingDirection": "rtl",
    "defaultLanguage": "orig",
    "languages": {
      "orig": {
        "label": "Original",
        "shortLabel": "ORIG",
        "pages": [
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/animiste-chapitre-1-028.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/animiste-chapitre-1-029.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/animiste-chapitre-1-030.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/animiste-chapitre-1-031.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/animiste-chapitre-1-032.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/animiste-chapitre-1-033.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/animiste-chapitre-1-034.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/animiste-chapitre-1-035.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/animiste-chapitre-1-036.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/animiste-chapitre-1-037.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/animiste-chapitre-1-038.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/animiste-chapitre-1-039.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/animiste-chapitre-1-040.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/animiste-chapitre-1-041.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/animiste-chapitre-1-042.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/animiste-chapitre-1-043.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/animiste-chapitre-1-059.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/animiste-chapitre-1-060.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/animiste-chapitre-1-061.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/animiste-chapitre-1-062.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/animiste-chapitre-1-063.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/penup-20251125-061251.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/penup-20251125-062542.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/penup-20251125-063434.jpg"),
          assetPath("assets/mangaka/complete-storyboards/gotenga-x-so/orig/penup-20251125-064358.jpg")
        ]
      }
    },
    "featured": false,
    "status": "draft",
    "visibility": "public",
    "description": "",
    "author": "",
    "date": "",
    "defaultReadingMode": "",
    "tags": [],
    "order": 0
  },
  {
    "id": "hana-s-first-appearance",
    "slug": "hana-s-first-appearance",
    "route": "/mangas/hana-s-first-appearance",
    "title": "Hana's first appearance",
    "edition": "",
    "banner": assetPath("assets/mangaka/complete-storyboards/hana-s-first-appearance/banner.jpg"),
    "presentationSection": "storyboard",
    "summary": "Sketch Storyboard",
    "genre": "",
    "role": "",
    "year": "",
    "readingDirection": "rtl",
    "defaultLanguage": "en",
    "languages": {
      "en": {
        "label": "English",
        "shortLabel": "ENG",
        "pages": [
          assetPath("assets/mangaka/complete-storyboards/hana-s-first-appearance/en/animiste-chapitre-1-064.jpg"),
          assetPath("assets/mangaka/complete-storyboards/hana-s-first-appearance/en/animiste-chapitre-1-065.jpg"),
          assetPath("assets/mangaka/complete-storyboards/hana-s-first-appearance/en/animiste-chapitre-1-066.jpg"),
          assetPath("assets/mangaka/complete-storyboards/hana-s-first-appearance/en/animiste-chapitre-1-076.jpg"),
          assetPath("assets/mangaka/complete-storyboards/hana-s-first-appearance/en/animiste-chapitre-1-077.jpg"),
          assetPath("assets/mangaka/complete-storyboards/hana-s-first-appearance/en/animiste-chapitre-1-078.jpg"),
          assetPath("assets/mangaka/complete-storyboards/hana-s-first-appearance/en/animiste-chapitre-1-079.jpg"),
          assetPath("assets/mangaka/complete-storyboards/hana-s-first-appearance/en/animiste-chapitre-1-080.jpg"),
          assetPath("assets/mangaka/complete-storyboards/hana-s-first-appearance/en/animiste-chapitre-1-081.jpg")
        ]
      }
    },
    "featured": false,
    "status": "draft",
    "visibility": "public",
    "description": "",
    "author": "",
    "date": "",
    "defaultReadingMode": "",
    "tags": [],
    "order": 0
  },
  {
    "id": "isekai-sketch",
    "slug": "isekai-sketch",
    "route": "/mangas/isekai-sketch",
    "title": "Isekai Sketch",
    "edition": "",
    "banner": assetPath("assets/mangaka/complete-storyboards/isekai-sketch/banner.jpg"),
    "presentationSection": "storyboard",
    "summary": "Sketch Storyboard",
    "genre": "",
    "role": "",
    "year": "",
    "readingDirection": "rtl",
    "defaultLanguage": "orig",
    "languages": {
      "orig": {
        "label": "Original",
        "shortLabel": "ORIG",
        "pages": [
          assetPath("assets/mangaka/complete-storyboards/isekai-sketch/orig/reincarne-dans-un-nouveau-monde-1-001.jpg"),
          assetPath("assets/mangaka/complete-storyboards/isekai-sketch/orig/reincarne-dans-un-nouveau-monde-1-002.jpg"),
          assetPath("assets/mangaka/complete-storyboards/isekai-sketch/orig/reincarne-dans-un-nouveau-monde-1-003.jpg"),
          assetPath("assets/mangaka/complete-storyboards/isekai-sketch/orig/reincarne-dans-un-nouveau-monde-1-004.jpg")
        ]
      }
    },
    "featured": false,
    "status": "draft",
    "visibility": "public",
    "description": "",
    "author": "",
    "date": "",
    "defaultReadingMode": "",
    "tags": [],
    "order": 0
  },
  {
    "id": "memory-team-mecha",
    "slug": "memory-team-mecha",
    "route": "/mangas/memory-team-mecha",
    "title": "Memory team mecha",
    "edition": "",
    "banner": assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/banner.jpg"),
    "presentationSection": "storyboard",
    "summary": "Sketch Storyboard",
    "genre": "",
    "role": "",
    "year": "",
    "readingDirection": "rtl",
    "defaultLanguage": "orig",
    "languages": {
      "orig": {
        "label": "Original",
        "shortLabel": "ORIG",
        "pages": [
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260510-081350.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260510-081357.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260510-083238.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260510-083507.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260510-084415.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260510-084537.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260511-004248.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260511-004404-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260511-004404.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260511-005420.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260511-011306.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260511-012554.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260511-013453.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260511-014820.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260511-015856.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260511-020133.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260511-021022.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260512-122540.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260512-122907.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260512-123525.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260512-123906.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260514-054742.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260514-060022.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260514-060037.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260514-082318.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260514-083817.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260514-084447.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260514-084831.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260514-090114.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260514-090249.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260514-090528.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260514-091124.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260514-091520.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260515-082126.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260515-082345.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260515-082956.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260515-083404.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260515-083602.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260515-083840.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260515-084104.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260515-085828-0.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260515-085828-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260515-085828.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260515-090428.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260515-090557-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260515-090557.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260515-090730.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260515-091054.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260516-091936.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260516-095420.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260516-100501.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260516-101310.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260516-102927.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260516-102941.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260516-103659.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260516-104107.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260516-104804.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260516-105133.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260516-105521.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260516-110407.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260516-111037.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260516-112149.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260516-112236.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260516-112327.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260516-112513.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260516-112931.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260516-113549.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260516-113709.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260517-101841.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260517-102034.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260517-102222.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260517-102806.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260517-110335.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260517-110342.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260517-110711.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260517-110735.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260517-111538-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260517-111538.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260517-113358.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/penup-20260517-122631.jpg"),
          assetPath("assets/mangaka/complete-storyboards/memory-team-mecha/orig/projet-20260519034929.jpg")
        ]
      }
    },
    "featured": false,
    "status": "draft",
    "visibility": "public",
    "description": "",
    "author": "",
    "date": "",
    "defaultReadingMode": "",
    "tags": [],
    "order": 0
  },
  {
    "id": "miss-doll-miss-marionette",
    "slug": "miss-doll-miss-marionette",
    "route": "/mangas/miss-doll-miss-marionette",
    "title": "Miss Doll & Miss Marionette",
    "edition": "",
    "banner": assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/banner.jpg"),
    "presentationSection": "storyboard",
    "summary": "Sketch Storyboard",
    "genre": "",
    "role": "",
    "year": "",
    "readingDirection": "rtl",
    "defaultLanguage": "orig",
    "languages": {
      "orig": {
        "label": "Original",
        "shortLabel": "ORIG",
        "pages": [
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251002085457.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251002085514.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251002085522-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251002085522.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251002090346-0.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251002090346-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251002090346.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251002125655.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251002125715.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251025040117.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251025040146.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251025040159.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251025040209.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251002125715-2.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251025040235.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251025045251.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251025045307.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251102115726-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251102115726.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251102115738.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251102115746.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251102115755.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251102115802.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251102115809-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251102115809.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251104120408.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251107012417.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251107012440.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251107012450.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251107012457.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251107012502.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251107012508.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251107012514.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251107012518.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251107012524.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251107012528.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251107012533.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251107012549.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251107012554.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251107012559.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251107012603.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251107012608.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251107012614.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251107012619.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109014104.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109014115.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109014140.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109014150.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109014205.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109014214.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109014240-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109014240.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109014247.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109014300.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109014406.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109014431.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109014440.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109014519.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109014529.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109014937.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109015056.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109015117.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109015130.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109015138.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109015145.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109015154.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109015319.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109015319-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109015319-10.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109015319-11-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109015319-11.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109015319-12.jpg"),
          assetPath("assets/mangaka/complete-storyboards/miss-doll-miss-marionette/orig/projet-20251109015319-13.jpg")
        ]
      }
    },
    "featured": false,
    "status": "draft",
    "visibility": "public",
    "description": "",
    "author": "",
    "date": "",
    "defaultReadingMode": "",
    "tags": [],
    "order": 0
  },
  {
    "id": "new-beginning-new-hope",
    "slug": "new-beginning-new-hope",
    "route": "/mangas/new-beginning-new-hope",
    "title": "New beginning – New hope",
    "edition": "",
    "banner": assetPath("assets/mangaka/complete-storyboards/new-beginning-new-hope/banner.jpg"),
    "presentationSection": "storyboard",
    "summary": "Sketch Storyboard",
    "genre": "",
    "role": "",
    "year": "",
    "readingDirection": "rtl",
    "defaultLanguage": "orig",
    "languages": {
      "orig": {
        "label": "Original",
        "shortLabel": "ORIG",
        "pages": [
          assetPath("assets/mangaka/complete-storyboards/new-beginning-new-hope/orig/animiste-chapitre-1-083.jpg"),
          assetPath("assets/mangaka/complete-storyboards/new-beginning-new-hope/orig/animiste-chapitre-1-084-1.jpg"),
          assetPath("assets/mangaka/complete-storyboards/new-beginning-new-hope/orig/animiste-chapitre-1-084.jpg"),
          assetPath("assets/mangaka/complete-storyboards/new-beginning-new-hope/orig/animiste-chapitre-1-085.jpg"),
          assetPath("assets/mangaka/complete-storyboards/new-beginning-new-hope/orig/animiste-chapitre-1-091.jpg"),
          assetPath("assets/mangaka/complete-storyboards/new-beginning-new-hope/orig/animiste-chapitre-1-092.jpg"),
          assetPath("assets/mangaka/complete-storyboards/new-beginning-new-hope/orig/animiste-chapitre-1-093.jpg"),
          assetPath("assets/mangaka/complete-storyboards/new-beginning-new-hope/orig/animiste-chapitre-1-094.jpg"),
          assetPath("assets/mangaka/complete-storyboards/new-beginning-new-hope/orig/animiste-chapitre-1-095.jpg"),
          assetPath("assets/mangaka/complete-storyboards/new-beginning-new-hope/orig/animiste-chapitre-1-096.jpg"),
          assetPath("assets/mangaka/complete-storyboards/new-beginning-new-hope/orig/animiste-chapitre-1-097.jpg"),
          assetPath("assets/mangaka/complete-storyboards/new-beginning-new-hope/orig/animiste-chapitre-1-098.jpg"),
          assetPath("assets/mangaka/complete-storyboards/new-beginning-new-hope/orig/animiste-chapitre-1-099.jpg"),
          assetPath("assets/mangaka/complete-storyboards/new-beginning-new-hope/orig/animiste-chapitre-1-100.jpg"),
          assetPath("assets/mangaka/complete-storyboards/new-beginning-new-hope/orig/animiste-chapitre-1-101.jpg"),
          assetPath("assets/mangaka/complete-storyboards/new-beginning-new-hope/orig/animiste-chapitre-1-102.jpg"),
          assetPath("assets/mangaka/complete-storyboards/new-beginning-new-hope/orig/animiste-chapitre-1-103.jpg")
        ]
      }
    },
    "featured": false,
    "status": "draft",
    "visibility": "public",
    "description": "",
    "author": "",
    "date": "",
    "defaultReadingMode": "",
    "tags": [],
    "order": 0
  },
  {
    "id": "rescue-x-the-energy-of-despair",
    "slug": "rescue-x-the-energy-of-despair",
    "route": "/mangas/rescue-x-the-energy-of-despair",
    "title": "Rescue X The Energy of Despair",
    "edition": "",
    "banner": assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/banner.jpg"),
    "presentationSection": "storyboard",
    "summary": "Sketch Storyboard",
    "genre": "",
    "role": "",
    "year": "",
    "readingDirection": "rtl",
    "defaultLanguage": "english",
    "languages": {
      "english": {
        "label": "ENGLISH",
        "shortLabel": "ENGLISH",
        "pages": [
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/english/bdsketch-003.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/english/bdsketch-005.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/english/bdsketch-007.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/english/bdsketch-008.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/english/bdsketch-009.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/english/bdsketch-010.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/english/bdsketch-011.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/english/bdsketch-015.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/english/bdsketch-016.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/english/bdsketch-017.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/english/bdsketch-018.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/english/bdsketch-020.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/english/bdsketch-021.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/english/bdsketch-022.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/english/bdsketch-030.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/english/bdsketch-031.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/english/bdsketch-032.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/english/bdsketch-033.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/english/bdsketch-034.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/english/bdsketch-035.jpg")
        ]
      },
      "french": {
        "label": "FRENCH",
        "shortLabel": "FRENCH",
        "pages": [
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/french/bdsketch-003.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/french/bdsketch-005.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/french/bdsketch-007.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/french/bdsketch-008.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/french/bdsketch-009.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/french/bdsketch-010.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/french/bdsketch-011.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/french/bdsketch-015.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/french/bdsketch-016.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/french/bdsketch-017.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/french/bdsketch-018.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/french/bdsketch-019.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/french/bdsketch-020.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/french/bdsketch-021.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/french/bdsketch-022.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/french/bdsketch-23.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/french/bdsketch-024.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/french/bdsketch-032.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/french/bdsketch-033.jpg"),
          assetPath("assets/mangaka/complete-storyboards/rescue-x-the-energy-of-despair/french/bdsketch-034.jpg")
        ]
      }
    },
    "featured": false,
    "status": "draft",
    "visibility": "public",
    "description": "",
    "author": "",
    "date": "",
    "defaultReadingMode": "",
    "tags": [],
    "order": 0
  }
];

export const mangas = mangaDefinitions.map((manga) => {
  const pages = manga.languages[manga.defaultLanguage].pages;

  return {
    ...manga,
    pages,
    pageCount: pages.length,
  };
});

export const getMangaById = (id) =>
  mangas.find((manga) => String(manga.id) === String(id));
